name = "PikaParser"
uuid = "3bbf5609-3e7b-44cd-8549-7c69f321e792"
authors = ["The developers of PikaParser.jl"]
version = "0.5.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.8, 0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
